#!/usr/bin/perl

# Dit scriptje laat de NOS teletext zien, GPL versie 2
# (c) 2001, 2002, 2003 by Bas Zoetekouw <bas@debian.org>
# All rights reserved.
# (c) 2013 Miek Gieben <miek@miek.nl>
# Complete rewrite.
# http://utopia.knoware.nl/users/eprebel/Communication/Prestel/index.html

# TODO: hold graphics

use LWP::Simple;
use Switch;
use strict;

my $color = 1;
if ((scalar @ARGV > 0) && ($ARGV[0] eq "-m")) { $color = 0; shift; }

# the first char is 32 (space), so index with ord('x') - 32
my @graphs = (
    "⠀", "⠁", "⠈", "⠉", "⠆", "⠇", "⠎", "⠏",   # 0x20-0x27
    "⠰", "⠱", "⠸", "⠹", "⠶", "⠷", "⠾", "⠿",   # 0x28-0x2f
    "⡀", "⡁", "⡈", "⡉", "⡆", "⡇", "⡎", "⡏",   # 0x30-0x37
    "⡰", "⡱", "⡸", "⡹", "⡶", "⡷", "⡾", "⡿",   # 0x38-0x3f
    "-", "A", "B", "C", "D", "E", "F", "G",   # 0x40-0x47
    "H", "I", "J", "K", "L", "M", "N", "O",   # 0x48-0x4f
    "P", "Q", "R", "S", "T", "U", "V", "W",   # 0x50-0x57
    "X", "Y", "Z", " ", " ", " ", " ", "#",   # 0x58-0x5f
    "⢀", "⢁", "⢈", "⢉", "⢆", "⢇", "⢎", "⢏",   # 0x60-0x67
    "⢰", "⢱", "⢸", "⢹", "⢶", "⢷", "⢾", "⢿",   # 0x68-0x6f
    "⣀", "⣁", "⣈", "⣉", "⣆", "⣇", "⣎", "⣏",   # 0x70-0x77
    "⣰", "⣱", "⣸", "⣹", "⣶", "⣷", "⣾", "⣿",   # 0x78-0x7f
);

my %specials = (
    "" => "\e[7m ",
    "" => "\e[0m \n ",
    "" => "⣿",
);

my %gcolors = (
    "" => "\e[31m",  #red        0x11
    "" => "\e[32m",  #green      0x12
    "" => "\e[33m",  #yellow     0x13
    "" => "\e[34m",  #blue       0x14
    "" => "\e[35m",  #blue       0x15
    "" => "\e[36m",  #blue       0x16
    "" => "\e[37m",  #white      0x17
    "" => ""      ,  #contiguous display  0x18
);

my %colors = (
    "" => "\e[31m",  #red        0x01
    "" => "\e[32m",  #green      0x01
    "" => "\e[33m",  #yellow     0x01
    "" => "\e[34m",  #blue       0x01
    "" => "\e[35m",  #magenta    0x01
    "" => "\e[36m",  #cyan       0x01
    "" => "\e[37m",  #white      0x01
    "" => "\e[30m",  #background to black  0x01
);

sub display(@) {
    # last line contains tt
    my $line = $_[-1]; $line =~ s/<pre>//; $line =~ s/<\/pre>//;
    my $i = 0;
    my $set = 0;    # 0: normal set, 1: graphics set
    foreach (split //, $line) {
        switch ($_) {
        case { exists $gcolors{$_} }   { print $gcolors{$_} if $color; print " "; $set = 1; }
        case { exists $specials{$_} }  { print $specials{$_}; }
        case { exists $colors{$_} }    { print $colors{$_} if $color; print " "; $set = 0; }
        else                           {
                                            if ($set == 0) { utf8::encode $_; print ; }
                                            if ($set == 1) { print $graphs[(ord $_) - 32]; }
                                       }
        }
        $i++;
        if ($i > 39) { print "\e[0m\n"; $i = 0; $set = 0; }
    }
}

my ($pag, $sub) = @ARGV;
$pag = "100" if (scalar @ARGV == 0);
$sub = "0"   if (scalar @ARGV <= 1);
display split /\n/, get "http://teletekst.e-office.com/g/android?p=${pag}-${sub}&id=" . time;
